version: 2

models:
  - name: stg_acra_companies
    description: "Staging model for ACRA companies data with data quality enhancements and business categorization"
    columns:
      - name: uen
        description: "Unique Entity Number - primary identifier for Singapore companies"
        tests:
          - not_null
          - unique
      - name: entity_name
        description: "Official registered name of the entity"
        tests:
          - not_null
      - name: entity_type
        description: "Legal structure type of the entity"
        tests:
          - not_null
      - name: entity_category
        description: "Standardized business entity category"
        tests:
          - accepted_values:
              values: ['PRIVATE_COMPANY', 'PUBLIC_COMPANY', 'LLP', 'PARTNERSHIP', 'SOLE_PROPRIETORSHIP', 'OTHER']
      - name: is_active
        description: "Boolean flag indicating if the entity is currently active"
        tests:
          - not_null
      - name: postal_region
        description: "Singapore postal region based on postal code"
        tests:
          - accepted_values:
              values: ['Central', 'North East', 'North West', 'South East', 'South West', 'West', 'Central West', 'Unknown']
      - name: registration_year
        description: "Year when the entity was registered"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1960
              max_value: 2024
      - name: quality_tier
        description: "Data quality assessment tier"
        tests:
          - accepted_values:
              values: ['HIGH', 'MEDIUM', 'LOW', 'VERY_LOW']
      - name: business_age_category
        description: "Business maturity classification based on registration age"
        tests:
          - accepted_values:
              values: ['NEW_BUSINESS', 'YOUNG_BUSINESS', 'MATURE_BUSINESS', 'ESTABLISHED_BUSINESS']
      - name: data_quality_score
        description: "Numerical data quality score (0-1)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1

  - name: stg_singstat_economics
    description: "Staging model for SingStat economic indicators with standardized categorization"
    columns:
      - name: table_id
        description: "SingStat table identifier"
        tests:
          - not_null
      - name: series_id
        description: "SingStat data series identifier"
        tests:
          - not_null
      - name: indicator_category
        description: "Economic indicator category classification"
        tests:
          - accepted_values:
              values: ['GDP', 'INFLATION', 'UNEMPLOYMENT', 'INTEREST_RATE', 'DEMOGRAPHICS', 'TRADE', 'HOUSING', 'MANUFACTURING', 'SERVICES', 'OTHER']
      - name: period_year
        description: "Year of the data point"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1960
              max_value: 2024
      - name: value_numeric
        description: "Numerical value of the economic indicator"
        tests:
          - not_null
      - name: frequency
        description: "Data collection frequency"
        tests:
          - accepted_values:
              values: ['QUARTERLY', 'ANNUAL', 'MONTHLY', 'OTHER']
      - name: unit_category
        description: "Standardized unit category"
        tests:
          - accepted_values:
              values: ['PERCENTAGE', 'CURRENCY_SGD', 'MILLIONS', 'BILLIONS', 'THOUSANDS', 'INDEX', 'RATE', 'OTHER']
      - name: data_recency
        description: "Data recency classification"
        tests:
          - accepted_values:
              values: ['RECENT', 'CURRENT_CYCLE', 'HISTORICAL', 'ARCHIVE']
      - name: quality_tier
        description: "Data quality assessment tier"
        tests:
          - accepted_values:
              values: ['HIGH', 'MEDIUM', 'LOW', 'VERY_LOW']

  - name: stg_ura_geospatial
    description: "Staging model for URA geospatial property data with enhanced property categorization"
    columns:
      - name: project
        description: "Property project name"
        tests:
          - not_null
      - name: property_category
        description: "Standardized property type category"
        tests:
          - accepted_values:
              values: ['HDB', 'CONDOMINIUM', 'LANDED', 'EXECUTIVE_CONDOMINIUM', 'APARTMENT', 'OTHER']
      - name: tenure_category
        description: "Property tenure classification"
        tests:
          - accepted_values:
              values: ['FREEHOLD', 'LEASEHOLD', 'LEASEHOLD_999', 'OTHER']
      - name: region
        description: "Singapore geographical region"
        tests:
          - accepted_values:
              values: ['CENTRAL', 'EAST', 'NORTH', 'WEST', 'OTHER']
      - name: property_age_category
        description: "Property age classification"
        tests:
          - accepted_values:
              values: ['NEW', 'MODERN', 'MATURE', 'OLD', 'UNKNOWN']
      - name: coordinate_system
        description: "Coordinate system validation status"
        tests:
          - accepted_values:
              values: ['VALID_SVY21', 'VALID_WGS84', 'INVALID_COORDINATES', 'NO_COORDINATES']
      - name: development_era
        description: "Historical development period classification"
        tests:
          - accepted_values:
              values: ['PRE_INDEPENDENCE', 'EARLY_DEVELOPMENT', 'RAPID_GROWTH', 'MILLENNIUM', 'MODERN', 'UNKNOWN']
      - name: market_segment
        description: "Property market segment classification"
        tests:
          - accepted_values:
              values: ['PUBLIC_HOUSING', 'SEMI_PRIVATE', 'PRIVATE_NON_LANDED', 'PRIVATE_LANDED', 'OTHER']
      - name: built_year
        description: "Year the property was built"
        tests:
          - dbt_utils.accepted_range:
              min_value: 1900
              max_value: 2024
              where: "built_year is not null"
      - name: quality_tier
        description: "Data quality assessment tier"
        tests:
          - accepted_values:
              values: ['HIGH', 'MEDIUM', 'LOW', 'VERY_LOW']

# Custom tests
tests:
  - name: test_acra_registration_date_logic
    description: "Ensure registration dates are logical and not in the future"
    sql: |
      select *
      from {{ ref('stg_acra_companies') }}
      where uen_issue_date > current_date()
        or uen_issue_date < '1960-01-01'
  
  - name: test_singstat_value_consistency
    description: "Check for extreme outliers in economic data"
    sql: |
      select *
      from {{ ref('stg_singstat_economics') }}
      where value_numeric > 1000000 or value_numeric < -1000000
  
  - name: test_ura_coordinate_bounds
    description: "Validate Singapore coordinate boundaries"
    sql: |
      select *
      from {{ ref('stg_ura_geospatial') }}
      where has_coordinates = true
        and (
          (coordinate_system = 'VALID_SVY21' and (x_coordinate < 2000 or x_coordinate > 50000 or y_coordinate < 15000 or y_coordinate > 55000))
          or
          (coordinate_system = 'VALID_WGS84' and (x_coordinate < 103.6 or x_coordinate > 104.0 or y_coordinate < 1.2 or y_coordinate > 1.5))
        )